version: '3.3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
    volumes:
      - postgres2:/var/lib/postgresql/data
    ports:
      - 5436:5436
    command: -p 5436

volumes:
  postgres2:
